#!/usr/bin/env bash

#	Script to install my dotfiles
#   Author: Deyusha69
#	url: https://github.com/Deyusha69

CRE=$(tput setaf 1)
CYE=$(tput setaf 3)
CGR=$(tput setaf 2)
CBL=$(tput setaf 4)
BLD=$(tput bold)
CNC=$(tput sgr0)
OK='\n\033[0;32m OK...\033[0m'

logo () {
	
	local text="${1:?}"
	echo -en "                                  
	               %%%                
	        %%%%%//%%%%%              
	      %%************%%%           
	  (%%//############*****%%
	%%%%%**###&&&&&&&&&###**//
	%%(**##&&&#########&&&##**
	%%(**##*****#####*****##**%%%
	%%(**##     *****     ##**
	   //##   @@**   @@   ##//
	     ##     **###     ##
	     #######     #####//
	       ###**&&&&&**###
	       &&&         &&&
	       &&&////   &&
	          &&//@@@**
	            ..***               
			  deyusha69 Script\n\n"
    printf ' %s [%s%s %s%s %s]%s\n\n' "${CRE}" "${CNC}" "${CYE}" "${text}" "${CNC}" "${CRE}" "${CNC}"
    sleep 2
}

	
logo "Welcome!"
printf '%sThis script will install needed dependencies and copy my dotfiles to your hyprland setup.%s\n\nThis installer script does NOT change any configuration of your system.\nIts just a script that copies and moves my dotfiles to your ~/.config directory\n\n' "${CRE}" "${CNC}"
sleep 3

while true; do
	read -rp " Do you wish to continue? [y/N]: " yn
		case $yn in
			[Yy]* ) break;;
			[Nn]* ) exit;;
			* ) printf " Error: just write 'y' or 'n'\n\n";;
		esac
    done
			clear

logo "Checking if yay is installed"

	if pacman -Qi yay >/dev/null 2>&1; then
		printf "Yay is installed\n\n"
	else
		printf "installing yay..\n\n"
		sudo pacman -Syu git && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si && cd
	fi
sleep 2
clear
		
logo "Installing needed packages.."

	yay -S hyprland-bin waybar-hyprland-git wlogout wofi dunst papirus-icon-theme catppuccin-gtk-theme-mocha \
					 polkit-gnome wlsunset swayidle udev-block-notify blueman brightnessctl swaylock-effects wofi-emoji-git \
					 wofi-calc wofi-wifi-menu-git playerctl grim slurp pipewire wireplumber xdg-desktop-portal-wlr \
					 wl-clipboard networkmanager nwg-look inotify-tools-git fnm
					 
	yay -S thunar thunar-archive-plugin firefox deluge-gtk wdisplays eog pavucontrol mpv file-roller \
		   kitty cava ranger zsh starship neovim viewnior noise-suppression-for-voice swaybg geany ttf-droid noto-fonts-emoji
			  
clear
			 
logo "Cloning Rice!"
printf "Cloning rice from https://github.com/Deyusha69/dotfiles\n\n"
git clone --depth=1 https://github.com/Deyusha69/dotfiles.git
sleep 2
clear

logo "Copying Rice.."
printf "Copying files to respective directories..\n\n"

if [ -d "$HOME/.config" ]; then
	cp -r ~/dotfiles/.config/* ~/.config
else
	mkdir -p ~/.config && cp -r ~/dotfiles/.config/* ~/.config
fi

if [ -d "$HOME/.icons" ]; then
	cp -r ~/dotfiles/.icons/* ~/.icons
else
	mkdir -p ~/.icons && cp -r ~/dotfiles/.icons/* ~/.icons
fi

if [ -d "$HOME/.local/bin" ]; then
	cp -r ~/dotfiles/.local/bin/* ~/.local/bin
else
	mkdir -p ~/.local/bin && cp -r ~/dotfiles/.local/bin/* ~/.local/bin
fi

if [ -d "$HOME/.local/share" ]; then
	cp -r ~/dotfiles/.local/share/* ~/.local/share
else
	mkdir -p ~/.local/share && cp -r ~/dotfiles/.local/share/* ~/.local/share
fi

cp -r ~/dotfiles/.gtkrc-2.0 ~
cp -r ~/dotfiles/.lessfilter ~
cp -r ~/dotfiles/.profile ~
cp -r ~/dotfiles/.zshenv ~

printf "\n\nFiles copied succesfully\n\n"
sleep 2
clear

logo "Reloading fonts.."
printf "Reloading fonts to make it usable \n\n"

## Reloading fonts
fc-cache -rv

chmod -R +x ~/.config/hypr/scripts/

printf "\n\nFonts reloaded succesfully!\n\n"
sleep 2
clear

logo "Installation finished"
printf "%sNow logout your session, select hyprland and log in.%s \n\n" "${CRE}" "${CNC}"
zsh
