#!/usr/bin/env bash

#	Script to install my dotfiles
#   Author: z0mbi3
#	url: https://github.com/Deyusha69

CRE=$(tput setaf 1)
CYE=$(tput setaf 3)
CGR=$(tput setaf 2)
CBL=$(tput setaf 4)
BLD=$(tput bold)
CNC=$(tput sgr0)
OK='\n\033[0;32m OK...\033[0m'

logo () {
	
	local text="${1:?}"
	echo -en "                                   

	               %%%                
	        %%%%%//%%%%%              
	      %%************%%%           
	  (%%//############*****%%
	%%%%%**###&&&&&&&&&###**//
	%%(**##&&&#########&&&##**
	%%(**##*****#####*****##**%%%
	%%(**##     *****     ##**
	   //##   @@**   @@   ##//
	     ##     **###     ##
	     #######     #####//
	       ###**&&&&&**###
	       &&&         &&&
	       &&&////   &&
	          &&//@@@**
	            ..***       

			  \n\n"
    printf ' %s [%s%s %s%s %s]%s\n\n' "${CRE}" "${CNC}" "${CYE}" "${text}" "${CNC}" "${CRE}" "${CNC}"
    sleep 2
}

	
logo "Welcome!"
printf '%sThis script will install needed dependencies and copy my dotfiles to your hyprland setup.%s\n\n' "${CRE}" "${CNC}"
sleep 5

while true; do
	read -rp " Do you wish to continue? [y/N]: " yn
		case $yn in
			[Yy]* ) break;;
			[Nn]* ) exit;;
			* ) printf " Error: just write 'y' or 'n'\n\n";;
		esac
    done
			clear
			
logo "Installing needed packages.."

dependencias=(base-devel dunst git geany ranger papirus-icon-theme wofi gvfs starship zsh thunar thunar-archive-plugin polkit-gnome swayidle blueman brightnessctl eog pavucontrol playerctl grim slurp pipewire wireplumber wf-recorder file-roller kitty viewnior wl-clipboard networkmanager noise-suppression-for-voice swaybg ttf-droid noto-fonts-emoji)

is_installed() {
  pacman -Qi $1 &> /dev/null
  return $?
}

printf "%s%sChecking for required packages...%s\n" "${BLD}" "${CBL}" "${CNC}"
for paquete in "${dependencias[@]}"
do
  if ! is_installed $paquete; then
    sudo pacman -S $paquete --noconfirm
    printf "\n"
  else
    printf '%s%s is already installed on your system!%s\n' "${CGR}" "$paquete" "${CNC}"
    sleep 1
  fi
done
sleep 2
clear

logo "Checking if yay is installed"

	if ! command -v yay &>/dev/null; then
		printf "%s%sError YAY is not installed%s\n" "${BLD}" "${CRE}" "${CNC}"
		sleep 1
		printf "%s%sInstalling YAY..%s\n\n" "${BLD}" "${CYE}" "${CNC}"
		sleep 1
		git clone https://aur.archlinux.org/yay-bin && cd yay-bin && makepkg -si && cd && rm -rf yay-bin
	else
		printf "%s%sYAY is already installed on your system%s\n" "${BLD}" "${CGR}" "${CNC}"
	fi
sleep 2
clear



logo "Cloning Rice!"
[ -e ~/dotfiles ] && rm -rf ~/dotfiles
printf "Cloning rice from https://github.com/Deyusha69/dotfiles\n\n"
git clone --depth=1 https://github.com/Deyusha69/dotfiles.git
sleep 2
clear


logo "Copying Rice.."
printf "Copying files to respective directories..\n"

if [ ! -d $HOME/.config ]; then
	mkdir -p $HOME/.config
	cp -r $HOME/dotfiles/.config/* $HOME/.config
else
	cp -r $HOME/dotfiles/.config/* $HOME/.config
fi

if [ ! -d $HOME/.local/bin ]; then
	mkdir -p $HOME/.local/bin
	cp -r $HOME/dotfiles/.local/bin/* $HOME/.local/bin
else
	cp -r $HOME/dotfiles/.local/bin/* $HOME/.local/bin
fi

if [ ! -d $HOME/.local/share/applications ]; then
	mkdir -p $HOME/.local/share/applications
	cp -r $HOME/dotfiles/.local/share/applications/* $HOME/.local/share/applications
else
	cp -r $HOME/dotfiles/.local/share/applications/* $HOME/.local/share/applications
fi

if [ ! -d $HOME/.local/share/fonts ]; then
	mkdir -p $HOME/.local/share/fonts
	cp -r $HOME/dotfiles/.local/share/fonts/* $HOME/.local/share/fonts
else
	cp -r $HOME/dotfiles/.local/share/fonts/* $HOME/.local/share/fonts
fi

if [ ! -d $HOME/.icons ]; then
	mkdir -p $HOME/.icons
	cp -r $HOME/dotfiles/.icons/* $HOME/.icons
else
	cp -r $HOME/dotfiles/.icons/* $HOME/.icons
fi

chmod -R +x ~/.config/hypr/scripts/
chmod +x ~/.config/hypr/autostart

printf "%s%sFiles copied succesfully!!%s\n" "${BLD}" "${CGR}" "${CNC}"
sleep 2
clear

logo "Installing needed packages from AUR"				 
yay -S hyprland-bin waybar-hyprland wlogout wlsunset udev-block-notify blueman swaylock-effects xdg-desktop-portal-hyprland-git firefox inotify-tools-git sddm-git --removemake --cleanafter
sleep 2	  
clear

logo "Installing Themes"				 
git clone https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme.git
cd Tokyo-Night-GTK-Theme/
sudo cp -r themes/Tokyonight-Dark-BL-LB /usr/share/themes/
cd
sleep 2	  
clear

logo "Reloading fonts.."
fc-cache -rv >/dev/null 2>&1
printf "%s%sFonts reloaded succesfully!%s\n" "${BLD}" "${CGR}" "${CNC}"
sleep 2
clear

logo "Enabling SDDM service"
sudo systemctl enable sddm
printf "%s%sDone!!%s\n" "${BLD}" "${CGR}" "${CNC}"
sleep 2
clear

logo "Installation finished"
printf "%s%sNow Reboot, select hyprland and log in.%s\n\n" "${BLD}" "${CRE}" "${CNC}"
chsh -s /usr/bin/zsh
sudo systemctl start sddm
